### PR TITLE
Ft sign up 161578108

### PR DESCRIPTION
**Pull request by Kibetchirchir**
**What does this PR do?**
This is the register page for the sendit project.

**Description of Task to be completed?**

1. Create the cancel and register buttons
2. Allow user to submit his/her bio-data
3. Intergrate with the theme of the site(top-Nav and footer).
4. Make sure there is a submition

**How should this be manually tested?**

1. Clone the repository at https://github.com/Kibetchirchir/SENDIT.git
2. click the SENDIT folder
3. then click the UI folder
4. finaly right click on the signup.html and choose the option to open using your favorite browser

What are the relevant pivotal tracker stories?
#161578108

**Screenshots**

on desktop(14")

screenshot from 2018-11-01 00-48-42

### CODE REVIEW

**Comment by ChegeBryan** [comment]
That label for `id number` but the placeholder is an `email` format

**Comment by Sm0k3s** [comment]
Good but I don't think the date of birth field is relevant

**Comment by Kibetchirchir** [comment]
@ChegeBryan Thank you noted i will fix the bug

**Comment by Kibetchirchir** [comment]
@Sm0k3s I think it is relevant since i am collecting bio-data of the person

**Comment by ChegeBryan** [comment]
@Kibetchirchir as @Sm0k3s says collecting the date birth will add more work when saving the data to a database

**Comment by Kibetchirchir** [comment]
@ChegeBryan  The data will be needed at a later stage like verifying password or official document

**Comment by Kitingu** [comment]
looking good but consider having a password field in the form which will be used to log in the user

**Pull request merged**
