### PR TITLE
Ft landing page 161613168

### PR DESCRIPTION
**Pull request by Kibetchirchir**
<b>What does this PR do?</b>
This is the landing page.

Description of Task to be completed?

1. Create the signup and sign in  buttons 
2. Create a text Area to tell users what SENDIT is about
3. Create a foot bar that gives links to various social media platforms.

How should this be manually tested?

1. Clone the repository at https://github.com/Kibetchirchir/SENDIT.git  
2. click the SENDIT folder 
3. then click the UI folder
4.  finaly right click on the index.html and choose the option to open using your favorite browser

What are the relevant pivotal tracker stories?
#161613168

Screenshots

on desktop(14")
screenshot from 2018-10-31 22-46-01

### CODE REVIEW

**Comment by SimonAwiti** [comment]
Nice work, I also prefer my work with not background pics

**Comment by MeshackKipkorir** [comment]
looks good

**Comment by Sm0k3s** [comment]
Nice

**Comment by ChegeBryan** [comment]
Nicely put... but the sign-up and the sign in button seem to lack a border :disappointed:

**Pull request merged**
